[package]
name = "xtask"
edition = "2021"
publish = false
version = "0.1.0"

[dependencies]


{{#if integration_test}}# This dependency should stay in line with your router version

{{else}}
{{#if branch}}
{{else}}

{{/if}}
{{/if}}
apollo-router-scaffold = { path = "{{integration_test}}apollo-router-scaffold" }
apollo-router-scaffold = { git = "https://github.com/apollographql/router.git", branch = "{{branch}}" }
apollo-router-scaffold = { git = "https://github.com/apollographql/router.git", tag = "v2.0.0-alpha.7" }
anyhow = "1.0.58"
clap = "4.0.32"
