[build]
  base    = "docs"
  publish = "public"
  command = "gatsby build"
  # Netlify tries to short-circuit when the build hasn't changed, but it's
  # presently wrong.  I would encourage removing this eventually, but for now,
  # we'll check to see if `/bin/false` returns true (it won't) as a gauge.
  ignore  = "/bin/false"
[build.environment]
  NODE_VERSION = "16"
  NPM_VERSION  = "8"
[context.production.environment]
  PREFIX_PATHS = "true"
[context.branch-deploy.environment]
  PREFIX_PATHS = "true"
[dev]
  command = "npm run build"
[context.dev.environment]
  SKIP_INDEXING = "false"
