global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'apollo-router'
    static_configs:
      - targets: ['host.docker.internal:9090']
    metrics_path: /metrics
    scrape_interval: 5s