use apollo_compiler::Schema;
use apollo_compiler::collections::IndexMap;
use apollo_compiler::collections::IndexSet;
use apollo_compiler::schema::ExtendedType;

use crate::error::Locations;
use crate::merger::hints::DEPRECATED_IMPLEMENTING_FIELD_WITHOUT_INTERFACE;
use crate::merger::hints::DEPRECATED_REASON_NULL;
use crate::supergraph::CompositionHint;

/// Apply compatibility transformations so that federation 2 supergraphs are
/// valid under the GraphQL September 2025 spec (used by federation 3 / Router 3).
/// Returns any hints generated by the transformations.
///
/// Currently handles two patterns:
/// 1. `@deprecated(reason: null)` — the `reason` argument is non-nullable in the
///    2025 spec. The `reason: null` argument is stripped, leaving a bare
///    `@deprecated` (which receives the default reason "No longer supported").
/// 2. `@deprecated` on an implementing field whose corresponding interface field
///    is *not* deprecated — disallowed by the 2025 spec. The directive is stripped
///    from the implementing field.
pub(crate) fn apply_fed3_compat(schema: &mut Schema) -> Vec<CompositionHint> {
    let mut hints = Vec::new();

    // Collect interface field deprecation status up front so we aren't
    // borrowing the schema while mutating it.
    let iface_deprecated = collect_interface_deprecated_fields(schema);

    for ty in schema.types.values_mut() {
        match ty {
            ExtendedType::Object(object) => {
                let object = object.make_mut();
                for field in object.fields.values_mut() {
                    let field_def = field.make_mut();
                    strip_deprecated_reason_null(&mut hints, &mut field_def.directives);
                }

                for iface_name in &object.implements_interfaces {
                    if let Some(deprecated_fields) = iface_deprecated.get(&iface_name.name) {
                        for field in object.fields.values_mut() {
                            let field_name = field.name.clone();
                            if !deprecated_fields.contains(&field_name) {
                                let field_def = field.make_mut();
                                strip_deprecated_without_interface(
                                    &mut hints,
                                    &mut field_def.directives,
                                    &object.name,
                                    &field_name,
                                    &iface_name.name,
                                );
                            }
                        }
                    }
                }
            }
            ExtendedType::Interface(interface) => {
                let interface = interface.make_mut();
                for field in interface.fields.values_mut() {
                    let field_def = field.make_mut();
                    strip_deprecated_reason_null(&mut hints, &mut field_def.directives);
                }

                for parent_iface_name in &interface.implements_interfaces {
                    if let Some(deprecated_fields) =
                        iface_deprecated.get(&parent_iface_name.name)
                    {
                        for field in interface.fields.values_mut() {
                            let field_name = field.name.clone();
                            if !deprecated_fields.contains(&field_name) {
                                let field_def = field.make_mut();
                                strip_deprecated_without_interface(
                                    &mut hints,
                                    &mut field_def.directives,
                                    &interface.name,
                                    &field_name,
                                    &parent_iface_name.name,
                                );
                            }
                        }
                    }
                }
            }
            _ => {}
        }
    }
    hints
}

/// Returns a map from interface name to the set of deprecated field names
/// for every interface type in the schema.
fn collect_interface_deprecated_fields(
    schema: &Schema,
) -> IndexMap<apollo_compiler::Name, IndexSet<apollo_compiler::Name>> {
    let mut result = IndexMap::default();
    for ty in schema.types.values() {
        if let ExtendedType::Interface(interface) = ty {
            let deprecated_fields: IndexSet<_> = interface
                .fields
                .iter()
                .filter(|(_, field)| has_deprecated(&field.directives))
                .map(|(name, _)| name.clone())
                .collect();
            result.insert(interface.name.clone(), deprecated_fields);
        }
    }
    result
}

/// Returns true if the directive list contains any `@deprecated` application.
fn has_deprecated(directives: &apollo_compiler::ast::DirectiveList) -> bool {
    directives.0.iter().any(|d| d.name == "deprecated")
}

/// Strip the `reason: null` argument from `@deprecated(reason: null)`,
/// leaving a bare `@deprecated` (which receives the default reason
/// "No longer supported"). Emits a hint for each occurrence.
fn strip_deprecated_reason_null(
    hints: &mut Vec<CompositionHint>,
    directives: &mut apollo_compiler::ast::DirectiveList,
) {
    for directive in directives.0.iter_mut() {
        if directive.name != "deprecated" {
            continue;
        }
        let has_reason_null = directive
            .specified_argument_by_name("reason")
            .is_some_and(|v| v.is_null());
        if has_reason_null {
            let directive = directive.make_mut();
            directive.arguments.retain(|arg| arg.name != "reason");
            hints.push(CompositionHint {
                definition: &DEPRECATED_REASON_NULL,
                message: "Stripped `reason: null` from `@deprecated` for Router 3 compatibility. \
                          Use a non-null reason or omit the argument."
                    .to_string(),
                locations: Locations::default(),
            });
        }
    }
}

/// Strip `@deprecated` from an implementing field when the corresponding
/// interface field is not deprecated, emitting a hint for each occurrence.
fn strip_deprecated_without_interface(
    hints: &mut Vec<CompositionHint>,
    directives: &mut apollo_compiler::ast::DirectiveList,
    type_name: &apollo_compiler::Name,
    field_name: &apollo_compiler::Name,
    interface_name: &apollo_compiler::Name,
) {
    if directives.0.iter().any(|d| d.name == "deprecated") {
        directives.0.retain(|d| d.name != "deprecated");
        hints.push(CompositionHint {
            definition: &DEPRECATED_IMPLEMENTING_FIELD_WITHOUT_INTERFACE,
            message: format!(
                "Stripped `@deprecated` from `{type_name}.{field_name}` because \
                 `{interface_name}.{field_name}` is not deprecated. Either deprecate \
                 the interface field or remove `@deprecated` from the implementation."
            ),
            locations: Locations::default(),
        });
    }
}

#[cfg(test)]
mod tests {
    use apollo_compiler::coord;

    use crate::composition::CompositionOptions;
    use crate::subgraph::typestate::Subgraph;
    use crate::supergraph::Supergraph;

    fn compose_supergraph(sdl: &str) -> (Supergraph<crate::supergraph::Satisfiable>, Vec<String>) {
        let subgraph = Subgraph::parse("test", "http://localhost", sdl).unwrap();
        let result =
            crate::composition::compose(vec![subgraph], CompositionOptions::default()).unwrap();
        let hints: Vec<_> = result.hints().iter().map(|h| h.code().to_string()).collect();
        (result, hints)
    }

    #[test]
    fn strips_deprecated_reason_null() {
        let sdl = r#"
            type Query {
                field: String @deprecated(reason: null)
            }
        "#;
        let (supergraph, hints) = compose_supergraph(sdl);
        assert!(
            hints.contains(&"DEPRECATED_REASON_NULL".to_string()),
            "Expected DEPRECATED_REASON_NULL hint, got: {hints:?}"
        );

        let schema = supergraph.schema().schema();
        let c = coord!(Query.field);
        let field = schema.type_field(&c.ty, &c.attribute).unwrap();
        assert!(
            field.directives.has("deprecated"),
            "Field should still have @deprecated (only reason: null stripped)"
        );
        let deprecated = field.directives.get("deprecated").unwrap();
        assert!(
            deprecated.specified_argument_by_name("reason").is_none(),
            "reason argument should have been stripped"
        );
    }

    #[test]
    fn preserves_deprecated_with_valid_reason() {
        let sdl = r#"
            type Query {
                field: String @deprecated(reason: "use newField")
                newField: String
            }
        "#;
        let (supergraph, hints) = compose_supergraph(sdl);
        assert!(
            !hints.contains(&"DEPRECATED_REASON_NULL".to_string()),
            "Should not emit DEPRECATED_REASON_NULL, got: {hints:?}"
        );

        let schema = supergraph.schema().schema();
        let c = coord!(Query.field);
        let field = schema.type_field(&c.ty, &c.attribute).unwrap();
        let deprecated = field.directives.get("deprecated").unwrap();
        assert!(
            deprecated.specified_argument_by_name("reason").is_some(),
            "reason argument should be preserved for valid reasons"
        );
    }

    #[test]
    fn strips_deprecated_implementing_field_without_interface() {
        let sdl = r#"
            extend schema
                @link(url: "https://specs.apollo.dev/federation/v2.0", import: ["@key", "@shareable"])

            type Query {
                node: Node
            }

            interface Node {
                id: ID!
                name: String
            }

            type User implements Node @key(fields: "id") {
                id: ID!
                name: String @deprecated(reason: "use displayName")
                displayName: String
            }
        "#;
        let (supergraph, hints) = compose_supergraph(sdl);
        assert!(
            hints.contains(&"DEPRECATED_IMPLEMENTING_FIELD_WITHOUT_INTERFACE".to_string()),
            "Expected DEPRECATED_IMPLEMENTING_FIELD_WITHOUT_INTERFACE hint, got: {hints:?}"
        );

        let schema = supergraph.schema().schema();
        let c = coord!(User.name);
        let field = schema.type_field(&c.ty, &c.attribute).unwrap();
        assert!(
            !field.directives.has("deprecated"),
            "@deprecated should have been stripped from User.name"
        );
    }

    #[test]
    fn allows_deprecated_implementing_field_when_interface_also_deprecated() {
        let sdl = r#"
            extend schema
                @link(url: "https://specs.apollo.dev/federation/v2.0", import: ["@key", "@shareable"])

            type Query {
                node: Node
            }

            interface Node {
                id: ID!
                name: String @deprecated(reason: "use displayName")
            }

            type User implements Node @key(fields: "id") {
                id: ID!
                name: String @deprecated(reason: "use displayName")
                displayName: String
            }
        "#;
        let (supergraph, hints) = compose_supergraph(sdl);
        assert!(
            !hints.contains(&"DEPRECATED_IMPLEMENTING_FIELD_WITHOUT_INTERFACE".to_string()),
            "Should not emit DEPRECATED_IMPLEMENTING_FIELD_WITHOUT_INTERFACE, got: {hints:?}"
        );

        let schema = supergraph.schema().schema();
        let c = coord!(User.name);
        let field = schema.type_field(&c.ty, &c.attribute).unwrap();
        assert!(
            field.directives.has("deprecated"),
            "@deprecated should be preserved when interface field is also deprecated"
        );
    }
}
