use apollo_compiler::Schema;
use apollo_compiler::schema::ExtendedType;

use crate::error::Locations;
use crate::merger::hints::DEPRECATED_IMPLEMENTING_FIELD_WITHOUT_INTERFACE;
use crate::merger::hints::DEPRECATED_REASON_NULL;
use crate::supergraph::CompositionHint;

/// Apply compatibility transformations so that federation 2 supergraphs are
/// valid under the GraphQL September 2025 spec (used by federation 3 / Router 3).
/// Returns any hints generated by the transformations.
///
/// Currently handles two patterns:
/// 1. `@deprecated(reason: null)` — the `reason` argument is non-nullable in the
///    2025 spec. The directive is stripped entirely because `reason: null` caused
///    graphql-js to report `isDeprecated: false` anyway, so removing it preserves
///    the existing runtime behavior.
/// 2. `@deprecated` on an implementing field whose corresponding interface field
///    is *not* deprecated — disallowed by the 2025 spec. The directive is stripped
///    from the implementing field.
pub(crate) fn apply_fed3_compat(schema: &mut Schema) -> Vec<CompositionHint> {
    let mut hints = Vec::new();

    // Collect interface field deprecation status up front so we aren't
    // borrowing the schema while mutating it.
    let interface_deprecated_fields = collect_interface_deprecated_fields(schema);

    for ty in schema.types.values_mut() {
        match ty {
            ExtendedType::Object(object) => {
                let object = object.make_mut();
                for field in object.fields.values_mut() {
                    let field_def = field.make_mut();
                    strip_deprecated_reason_null(&mut hints, &mut field_def.directives);
                }

                for iface_name in &object.implements_interfaces {
                    if let Some(iface_fields) = interface_deprecated_fields
                        .iter()
                        .find(|(name, _)| name == &iface_name.name)
                        .map(|(_, fields)| fields)
                    {
                        for field in object.fields.values_mut() {
                            let field_name = field.name.clone();
                            let interface_field_is_deprecated = iface_fields
                                .iter()
                                .find(|(name, _)| *name == field_name)
                                .map(|(_, deprecated)| *deprecated)
                                .unwrap_or(false);

                            if !interface_field_is_deprecated {
                                let field_def = field.make_mut();
                                strip_deprecated_without_interface(
                                    &mut hints,
                                    &mut field_def.directives,
                                    &object.name,
                                    &field_name,
                                    &iface_name.name,
                                );
                            }
                        }
                    }
                }
            }
            ExtendedType::Interface(interface) => {
                let interface = interface.make_mut();
                for field in interface.fields.values_mut() {
                    let field_def = field.make_mut();
                    strip_deprecated_reason_null(&mut hints, &mut field_def.directives);
                }

                for parent_iface_name in &interface.implements_interfaces {
                    if let Some(parent_fields) = interface_deprecated_fields
                        .iter()
                        .find(|(name, _)| name == &parent_iface_name.name)
                        .map(|(_, fields)| fields)
                    {
                        for field in interface.fields.values_mut() {
                            let field_name = field.name.clone();
                            let parent_field_is_deprecated = parent_fields
                                .iter()
                                .find(|(name, _)| *name == field_name)
                                .map(|(_, deprecated)| *deprecated)
                                .unwrap_or(false);

                            if !parent_field_is_deprecated {
                                let field_def = field.make_mut();
                                strip_deprecated_without_interface(
                                    &mut hints,
                                    &mut field_def.directives,
                                    &interface.name,
                                    &field_name,
                                    &parent_iface_name.name,
                                );
                            }
                        }
                    }
                }
            }
            _ => {}
        }
    }
    hints
}

/// Returns a list of (interface_name, [(field_name, is_deprecated)]) for every
/// interface type in the schema.
fn collect_interface_deprecated_fields(
    schema: &Schema,
) -> Vec<(apollo_compiler::Name, Vec<(apollo_compiler::Name, bool)>)> {
    let mut result = Vec::new();
    for ty in schema.types.values() {
        if let ExtendedType::Interface(interface) = ty {
            let fields: Vec<_> = interface
                .fields
                .iter()
                .map(|(name, field)| {
                    let is_deprecated = has_effective_deprecated(&field.directives);
                    (name.clone(), is_deprecated)
                })
                .collect();
            result.push((interface.name.clone(), fields));
        }
    }
    result
}

/// Returns true if the directive list contains `@deprecated` with an effective
/// deprecation (i.e. NOT `@deprecated(reason: null)`, which graphql-js treats
/// as not deprecated).
fn has_effective_deprecated(directives: &apollo_compiler::ast::DirectiveList) -> bool {
    directives.0.iter().any(|d| {
        d.name == "deprecated"
            && !d
                .specified_argument_by_name("reason")
                .is_some_and(|v| v.is_null())
    })
}

/// Strip `@deprecated(reason: null)` from a directive list, emitting a hint
/// for each occurrence.
fn strip_deprecated_reason_null(
    hints: &mut Vec<CompositionHint>,
    directives: &mut apollo_compiler::ast::DirectiveList,
) {
    let had_deprecated_reason_null = directives.0.iter().any(|d| {
        d.name == "deprecated"
            && d.specified_argument_by_name("reason")
                .is_some_and(|v| v.is_null())
    });

    if had_deprecated_reason_null {
        directives.0.retain(|d| {
            !(d.name == "deprecated"
                && d.specified_argument_by_name("reason")
                    .is_some_and(|v| v.is_null()))
        });
        hints.push(CompositionHint {
            definition: &DEPRECATED_REASON_NULL,
            message: "`@deprecated(reason: null)` is not valid in the GraphQL \
                      September 2025 specification because the `reason` argument is \
                      now non-nullable. The directive has been removed to maintain \
                      compatibility with Router 3. Update your subgraph to remove \
                      the `reason: null` argument."
                .to_string(),
            locations: Locations::default(),
        });
    }
}

/// Strip `@deprecated` from an implementing field when the corresponding
/// interface field is not deprecated, emitting a hint for each occurrence.
fn strip_deprecated_without_interface(
    hints: &mut Vec<CompositionHint>,
    directives: &mut apollo_compiler::ast::DirectiveList,
    type_name: &apollo_compiler::Name,
    field_name: &apollo_compiler::Name,
    interface_name: &apollo_compiler::Name,
) {
    if directives.0.iter().any(|d| d.name == "deprecated") {
        directives.0.retain(|d| d.name != "deprecated");
        hints.push(CompositionHint {
            definition: &DEPRECATED_IMPLEMENTING_FIELD_WITHOUT_INTERFACE,
            message: format!(
                "Field `{type_name}.{field_name}` is marked `@deprecated` but \
                 the corresponding field on interface `{interface_name}` is not \
                 deprecated. The GraphQL September 2025 specification does not \
                 allow this. The `@deprecated` directive has been removed for \
                 Router 3 compatibility. Either deprecate \
                 `{interface_name}.{field_name}` or remove `@deprecated` from \
                 `{type_name}.{field_name}`."
            ),
            locations: Locations::default(),
        });
    }
}

#[cfg(test)]
mod tests {
    use crate::composition::CompositionOptions;
    use crate::subgraph::typestate::Subgraph;

    fn compose_and_get_hints(sdl: &str) -> (Vec<String>, bool) {
        let subgraph = Subgraph::parse("test", "http://localhost", sdl).unwrap();
        let result = crate::composition::compose(vec![subgraph], CompositionOptions::default());
        match result {
            Ok(supergraph) => {
                let hints: Vec<_> = supergraph
                    .hints()
                    .iter()
                    .map(|h| h.code().to_string())
                    .collect();
                (hints, true)
            }
            Err(failure) => {
                let hints: Vec<_> = failure
                    .hints
                    .iter()
                    .map(|h| h.code().to_string())
                    .collect();
                (hints, false)
            }
        }
    }

    #[test]
    fn strips_deprecated_reason_null() {
        let sdl = r#"
            type Query {
                field: String @deprecated(reason: null)
            }
        "#;
        let (hints, success) = compose_and_get_hints(sdl);
        assert!(success, "Composition should succeed");
        assert!(
            hints.contains(&"DEPRECATED_REASON_NULL".to_string()),
            "Expected DEPRECATED_REASON_NULL hint, got: {hints:?}"
        );
    }

    #[test]
    fn preserves_deprecated_with_valid_reason() {
        let sdl = r#"
            type Query {
                field: String @deprecated(reason: "use newField")
                newField: String
            }
        "#;
        let (hints, success) = compose_and_get_hints(sdl);
        assert!(success, "Composition should succeed");
        assert!(
            !hints.contains(&"DEPRECATED_REASON_NULL".to_string()),
            "Should not emit DEPRECATED_REASON_NULL, got: {hints:?}"
        );
    }

    #[test]
    fn strips_deprecated_implementing_field_without_interface() {
        let sdl = r#"
            extend schema
                @link(url: "https://specs.apollo.dev/federation/v2.0", import: ["@key", "@shareable"])

            type Query {
                node: Node
            }

            interface Node {
                id: ID!
                name: String
            }

            type User implements Node @key(fields: "id") {
                id: ID!
                name: String @deprecated(reason: "use displayName")
                displayName: String
            }
        "#;
        let (hints, success) = compose_and_get_hints(sdl);
        assert!(success, "Composition should succeed");
        assert!(
            hints.contains(
                &"DEPRECATED_IMPLEMENTING_FIELD_WITHOUT_INTERFACE".to_string()
            ),
            "Expected DEPRECATED_IMPLEMENTING_FIELD_WITHOUT_INTERFACE hint, got: {hints:?}"
        );
    }

    #[test]
    fn allows_deprecated_implementing_field_when_interface_also_deprecated() {
        let sdl = r#"
            extend schema
                @link(url: "https://specs.apollo.dev/federation/v2.0", import: ["@key", "@shareable"])

            type Query {
                node: Node
            }

            interface Node {
                id: ID!
                name: String @deprecated(reason: "use displayName")
            }

            type User implements Node @key(fields: "id") {
                id: ID!
                name: String @deprecated(reason: "use displayName")
                displayName: String
            }
        "#;
        let (hints, success) = compose_and_get_hints(sdl);
        assert!(success, "Composition should succeed");
        assert!(
            !hints.contains(
                &"DEPRECATED_IMPLEMENTING_FIELD_WITHOUT_INTERFACE".to_string()
            ),
            "Should not emit DEPRECATED_IMPLEMENTING_FIELD_WITHOUT_INTERFACE, got: {hints:?}"
        );
    }

}
