extend schema
  @link(url: "https://specs.apollo.dev/federation/v2.12", import: ["@key"])

type Query {
  svc23_item0(id: ID!): Svc23Item0
  svc23_item1(id: ID!): Svc23Item1
  svc23_item2(id: ID!): Svc23Item2
  svc23_item3(id: ID!): Svc23Item3
  svc23_item4(id: ID!): Svc23Item4
  svc23_item5(id: ID!): Svc23Item5
  svc23_item6(id: ID!): Svc23Item6
  svc23_item7(id: ID!): Svc23Item7
  svc23_shared0(id: ID!): Shared0
  svc23_shared1(id: ID!): Shared1
  svc23_shared2(id: ID!): Shared2
  svc23_shared3(id: ID!): Shared3
}

type Svc23Item0 {
  id: ID!
  name: String
  value: Int
}

type Svc23Item1 {
  id: ID!
  name: String
  value: Int
}

type Svc23Item2 {
  id: ID!
  name: String
  value: Int
}

type Svc23Item3 {
  id: ID!
  name: String
  value: Int
}

type Svc23Item4 {
  id: ID!
  name: String
  value: Int
}

type Svc23Item5 {
  id: ID!
  name: String
  value: Int
}

type Svc23Item6 {
  id: ID!
  name: String
  value: Int
}

type Svc23Item7 {
  id: ID!
  name: String
  value: Int
}

type Shared0 @key(fields: "id") {
  id: ID!
  s23_a: String
  s23_b: String
}

type Shared1 @key(fields: "id") {
  id: ID!
  s23_a: String
  s23_b: String
}

type Shared2 @key(fields: "id") {
  id: ID!
  s23_a: String
  s23_b: String
}

type Shared3 @key(fields: "id") {
  id: ID!
  s23_a: String
  s23_b: String
}
