extend schema
  @link(url: "https://specs.apollo.dev/federation/v2.12", import: ["@key"])

type Query {
  svc28_item0(id: ID!): Svc28Item0
  svc28_item1(id: ID!): Svc28Item1
  svc28_item2(id: ID!): Svc28Item2
  svc28_item3(id: ID!): Svc28Item3
  svc28_item4(id: ID!): Svc28Item4
  svc28_item5(id: ID!): Svc28Item5
  svc28_item6(id: ID!): Svc28Item6
  svc28_item7(id: ID!): Svc28Item7
  svc28_shared0(id: ID!): Shared0
  svc28_shared1(id: ID!): Shared1
  svc28_shared2(id: ID!): Shared2
  svc28_shared3(id: ID!): Shared3
}

type Svc28Item0 {
  id: ID!
  name: String
  value: Int
}

type Svc28Item1 {
  id: ID!
  name: String
  value: Int
}

type Svc28Item2 {
  id: ID!
  name: String
  value: Int
}

type Svc28Item3 {
  id: ID!
  name: String
  value: Int
}

type Svc28Item4 {
  id: ID!
  name: String
  value: Int
}

type Svc28Item5 {
  id: ID!
  name: String
  value: Int
}

type Svc28Item6 {
  id: ID!
  name: String
  value: Int
}

type Svc28Item7 {
  id: ID!
  name: String
  value: Int
}

type Shared0 @key(fields: "id") {
  id: ID!
  s28_a: String
  s28_b: String
}

type Shared1 @key(fields: "id") {
  id: ID!
  s28_a: String
  s28_b: String
}

type Shared2 @key(fields: "id") {
  id: ID!
  s28_a: String
  s28_b: String
}

type Shared3 @key(fields: "id") {
  id: ID!
  s28_a: String
  s28_b: String
}
