extend schema
  @link(url: "https://specs.apollo.dev/federation/v2.12", import: ["@key"])

type Query {
  svc24_item0(id: ID!): Svc24Item0
  svc24_item1(id: ID!): Svc24Item1
  svc24_item2(id: ID!): Svc24Item2
  svc24_item3(id: ID!): Svc24Item3
  svc24_item4(id: ID!): Svc24Item4
  svc24_item5(id: ID!): Svc24Item5
  svc24_item6(id: ID!): Svc24Item6
  svc24_item7(id: ID!): Svc24Item7
  svc24_shared0(id: ID!): Shared0
  svc24_shared1(id: ID!): Shared1
  svc24_shared2(id: ID!): Shared2
  svc24_shared3(id: ID!): Shared3
}

type Svc24Item0 {
  id: ID!
  name: String
  value: Int
}

type Svc24Item1 {
  id: ID!
  name: String
  value: Int
}

type Svc24Item2 {
  id: ID!
  name: String
  value: Int
}

type Svc24Item3 {
  id: ID!
  name: String
  value: Int
}

type Svc24Item4 {
  id: ID!
  name: String
  value: Int
}

type Svc24Item5 {
  id: ID!
  name: String
  value: Int
}

type Svc24Item6 {
  id: ID!
  name: String
  value: Int
}

type Svc24Item7 {
  id: ID!
  name: String
  value: Int
}

type Shared0 @key(fields: "id") {
  id: ID!
  s24_a: String
  s24_b: String
}

type Shared1 @key(fields: "id") {
  id: ID!
  s24_a: String
  s24_b: String
}

type Shared2 @key(fields: "id") {
  id: ID!
  s24_a: String
  s24_b: String
}

type Shared3 @key(fields: "id") {
  id: ID!
  s24_a: String
  s24_b: String
}
