extend schema
  @link(url: "https://specs.apollo.dev/federation/v2.12", import: ["@key"])

type Query {
  svc44_item0(id: ID!): Svc44Item0
  svc44_item1(id: ID!): Svc44Item1
  svc44_item2(id: ID!): Svc44Item2
  svc44_item3(id: ID!): Svc44Item3
  svc44_item4(id: ID!): Svc44Item4
  svc44_item5(id: ID!): Svc44Item5
  svc44_item6(id: ID!): Svc44Item6
  svc44_item7(id: ID!): Svc44Item7
  svc44_shared0(id: ID!): Shared0
  svc44_shared1(id: ID!): Shared1
  svc44_shared2(id: ID!): Shared2
  svc44_shared3(id: ID!): Shared3
}

type Svc44Item0 {
  id: ID!
  name: String
  value: Int
}

type Svc44Item1 {
  id: ID!
  name: String
  value: Int
}

type Svc44Item2 {
  id: ID!
  name: String
  value: Int
}

type Svc44Item3 {
  id: ID!
  name: String
  value: Int
}

type Svc44Item4 {
  id: ID!
  name: String
  value: Int
}

type Svc44Item5 {
  id: ID!
  name: String
  value: Int
}

type Svc44Item6 {
  id: ID!
  name: String
  value: Int
}

type Svc44Item7 {
  id: ID!
  name: String
  value: Int
}

type Shared0 @key(fields: "id") {
  id: ID!
  s44_a: String
  s44_b: String
}

type Shared1 @key(fields: "id") {
  id: ID!
  s44_a: String
  s44_b: String
}

type Shared2 @key(fields: "id") {
  id: ID!
  s44_a: String
  s44_b: String
}

type Shared3 @key(fields: "id") {
  id: ID!
  s44_a: String
  s44_b: String
}
