extend schema
  @link(url: "https://specs.apollo.dev/federation/v2.12", import: ["@key"])

type Query {
  svc45_item0(id: ID!): Svc45Item0
  svc45_item1(id: ID!): Svc45Item1
  svc45_item2(id: ID!): Svc45Item2
  svc45_item3(id: ID!): Svc45Item3
  svc45_item4(id: ID!): Svc45Item4
  svc45_item5(id: ID!): Svc45Item5
  svc45_item6(id: ID!): Svc45Item6
  svc45_item7(id: ID!): Svc45Item7
  svc45_shared0(id: ID!): Shared0
  svc45_shared1(id: ID!): Shared1
  svc45_shared2(id: ID!): Shared2
  svc45_shared3(id: ID!): Shared3
}

type Svc45Item0 {
  id: ID!
  name: String
  value: Int
}

type Svc45Item1 {
  id: ID!
  name: String
  value: Int
}

type Svc45Item2 {
  id: ID!
  name: String
  value: Int
}

type Svc45Item3 {
  id: ID!
  name: String
  value: Int
}

type Svc45Item4 {
  id: ID!
  name: String
  value: Int
}

type Svc45Item5 {
  id: ID!
  name: String
  value: Int
}

type Svc45Item6 {
  id: ID!
  name: String
  value: Int
}

type Svc45Item7 {
  id: ID!
  name: String
  value: Int
}

type Shared0 @key(fields: "id") {
  id: ID!
  s45_a: String
  s45_b: String
}

type Shared1 @key(fields: "id") {
  id: ID!
  s45_a: String
  s45_b: String
}

type Shared2 @key(fields: "id") {
  id: ID!
  s45_a: String
  s45_b: String
}

type Shared3 @key(fields: "id") {
  id: ID!
  s45_a: String
  s45_b: String
}
