extend schema
  @link(url: "https://specs.apollo.dev/federation/v2.12", import: ["@key"])

type Query {
  svc49_item0(id: ID!): Svc49Item0
  svc49_item1(id: ID!): Svc49Item1
  svc49_item2(id: ID!): Svc49Item2
  svc49_item3(id: ID!): Svc49Item3
  svc49_item4(id: ID!): Svc49Item4
  svc49_item5(id: ID!): Svc49Item5
  svc49_item6(id: ID!): Svc49Item6
  svc49_item7(id: ID!): Svc49Item7
  svc49_shared0(id: ID!): Shared0
  svc49_shared1(id: ID!): Shared1
  svc49_shared2(id: ID!): Shared2
  svc49_shared3(id: ID!): Shared3
}

type Svc49Item0 {
  id: ID!
  name: String
  value: Int
}

type Svc49Item1 {
  id: ID!
  name: String
  value: Int
}

type Svc49Item2 {
  id: ID!
  name: String
  value: Int
}

type Svc49Item3 {
  id: ID!
  name: String
  value: Int
}

type Svc49Item4 {
  id: ID!
  name: String
  value: Int
}

type Svc49Item5 {
  id: ID!
  name: String
  value: Int
}

type Svc49Item6 {
  id: ID!
  name: String
  value: Int
}

type Svc49Item7 {
  id: ID!
  name: String
  value: Int
}

type Shared0 @key(fields: "id") {
  id: ID!
  s49_a: String
  s49_b: String
}

type Shared1 @key(fields: "id") {
  id: ID!
  s49_a: String
  s49_b: String
}

type Shared2 @key(fields: "id") {
  id: ID!
  s49_a: String
  s49_b: String
}

type Shared3 @key(fields: "id") {
  id: ID!
  s49_a: String
  s49_b: String
}
