extend schema
  @link(url: "https://specs.apollo.dev/federation/v2.12", import: ["@key"])

type Query {
  svc42_item0(id: ID!): Svc42Item0
  svc42_item1(id: ID!): Svc42Item1
  svc42_item2(id: ID!): Svc42Item2
  svc42_item3(id: ID!): Svc42Item3
  svc42_item4(id: ID!): Svc42Item4
  svc42_item5(id: ID!): Svc42Item5
  svc42_item6(id: ID!): Svc42Item6
  svc42_item7(id: ID!): Svc42Item7
  svc42_shared0(id: ID!): Shared0
  svc42_shared1(id: ID!): Shared1
  svc42_shared2(id: ID!): Shared2
  svc42_shared3(id: ID!): Shared3
}

type Svc42Item0 {
  id: ID!
  name: String
  value: Int
}

type Svc42Item1 {
  id: ID!
  name: String
  value: Int
}

type Svc42Item2 {
  id: ID!
  name: String
  value: Int
}

type Svc42Item3 {
  id: ID!
  name: String
  value: Int
}

type Svc42Item4 {
  id: ID!
  name: String
  value: Int
}

type Svc42Item5 {
  id: ID!
  name: String
  value: Int
}

type Svc42Item6 {
  id: ID!
  name: String
  value: Int
}

type Svc42Item7 {
  id: ID!
  name: String
  value: Int
}

type Shared0 @key(fields: "id") {
  id: ID!
  s42_a: String
  s42_b: String
}

type Shared1 @key(fields: "id") {
  id: ID!
  s42_a: String
  s42_b: String
}

type Shared2 @key(fields: "id") {
  id: ID!
  s42_a: String
  s42_b: String
}

type Shared3 @key(fields: "id") {
  id: ID!
  s42_a: String
  s42_b: String
}
