extend schema
  @link(url: "https://specs.apollo.dev/federation/v2.12", import: ["@key"])

type Query {
  svc5_item0(id: ID!): Svc5Item0
  svc5_item1(id: ID!): Svc5Item1
  svc5_item2(id: ID!): Svc5Item2
  svc5_item3(id: ID!): Svc5Item3
  svc5_item4(id: ID!): Svc5Item4
  svc5_item5(id: ID!): Svc5Item5
  svc5_item6(id: ID!): Svc5Item6
  svc5_item7(id: ID!): Svc5Item7
  svc5_shared0(id: ID!): Shared0
  svc5_shared1(id: ID!): Shared1
  svc5_shared2(id: ID!): Shared2
  svc5_shared3(id: ID!): Shared3
}

type Svc5Item0 {
  id: ID!
  name: String
  value: Int
}

type Svc5Item1 {
  id: ID!
  name: String
  value: Int
}

type Svc5Item2 {
  id: ID!
  name: String
  value: Int
}

type Svc5Item3 {
  id: ID!
  name: String
  value: Int
}

type Svc5Item4 {
  id: ID!
  name: String
  value: Int
}

type Svc5Item5 {
  id: ID!
  name: String
  value: Int
}

type Svc5Item6 {
  id: ID!
  name: String
  value: Int
}

type Svc5Item7 {
  id: ID!
  name: String
  value: Int
}

type Shared0 @key(fields: "id") {
  id: ID!
  s5_a: String
  s5_b: String
}

type Shared1 @key(fields: "id") {
  id: ID!
  s5_a: String
  s5_b: String
}

type Shared2 @key(fields: "id") {
  id: ID!
  s5_a: String
  s5_b: String
}

type Shared3 @key(fields: "id") {
  id: ID!
  s5_a: String
  s5_b: String
}
