extend schema
  @link(url: "https://specs.apollo.dev/federation/v2.12", import: ["@key"])

type Query {
  svc53_item0(id: ID!): Svc53Item0
  svc53_item1(id: ID!): Svc53Item1
  svc53_item2(id: ID!): Svc53Item2
  svc53_item3(id: ID!): Svc53Item3
  svc53_item4(id: ID!): Svc53Item4
  svc53_item5(id: ID!): Svc53Item5
  svc53_item6(id: ID!): Svc53Item6
  svc53_item7(id: ID!): Svc53Item7
  svc53_shared0(id: ID!): Shared0
  svc53_shared1(id: ID!): Shared1
  svc53_shared2(id: ID!): Shared2
  svc53_shared3(id: ID!): Shared3
}

type Svc53Item0 {
  id: ID!
  name: String
  value: Int
}

type Svc53Item1 {
  id: ID!
  name: String
  value: Int
}

type Svc53Item2 {
  id: ID!
  name: String
  value: Int
}

type Svc53Item3 {
  id: ID!
  name: String
  value: Int
}

type Svc53Item4 {
  id: ID!
  name: String
  value: Int
}

type Svc53Item5 {
  id: ID!
  name: String
  value: Int
}

type Svc53Item6 {
  id: ID!
  name: String
  value: Int
}

type Svc53Item7 {
  id: ID!
  name: String
  value: Int
}

type Shared0 @key(fields: "id") {
  id: ID!
  s53_a: String
  s53_b: String
}

type Shared1 @key(fields: "id") {
  id: ID!
  s53_a: String
  s53_b: String
}

type Shared2 @key(fields: "id") {
  id: ID!
  s53_a: String
  s53_b: String
}

type Shared3 @key(fields: "id") {
  id: ID!
  s53_a: String
  s53_b: String
}
