extend schema
  @link(url: "https://specs.apollo.dev/federation/v2.12", import: ["@key"])

type Query {
  svc54_item0(id: ID!): Svc54Item0
  svc54_item1(id: ID!): Svc54Item1
  svc54_item2(id: ID!): Svc54Item2
  svc54_item3(id: ID!): Svc54Item3
  svc54_item4(id: ID!): Svc54Item4
  svc54_item5(id: ID!): Svc54Item5
  svc54_item6(id: ID!): Svc54Item6
  svc54_item7(id: ID!): Svc54Item7
  svc54_shared0(id: ID!): Shared0
  svc54_shared1(id: ID!): Shared1
  svc54_shared2(id: ID!): Shared2
  svc54_shared3(id: ID!): Shared3
}

type Svc54Item0 {
  id: ID!
  name: String
  value: Int
}

type Svc54Item1 {
  id: ID!
  name: String
  value: Int
}

type Svc54Item2 {
  id: ID!
  name: String
  value: Int
}

type Svc54Item3 {
  id: ID!
  name: String
  value: Int
}

type Svc54Item4 {
  id: ID!
  name: String
  value: Int
}

type Svc54Item5 {
  id: ID!
  name: String
  value: Int
}

type Svc54Item6 {
  id: ID!
  name: String
  value: Int
}

type Svc54Item7 {
  id: ID!
  name: String
  value: Int
}

type Shared0 @key(fields: "id") {
  id: ID!
  s54_a: String
  s54_b: String
}

type Shared1 @key(fields: "id") {
  id: ID!
  s54_a: String
  s54_b: String
}

type Shared2 @key(fields: "id") {
  id: ID!
  s54_a: String
  s54_b: String
}

type Shared3 @key(fields: "id") {
  id: ID!
  s54_a: String
  s54_b: String
}
