version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@1.2.0

parameters:
  run_tests:
    type: boolean
    default: false

workflows:
  setup:
    jobs:
      - path-filtering/filter:
          base-revision: dev
          config-path: .circleci/continue_config.yml
          mapping: |
            apollo-router/src/.* run_tests true
            apollo-router/tests/.* run_tests true
            apollo-router/benches/.* run_tests true
            Cargo\.toml run_tests true
            Cargo\.lock run_tests true
            rust-toolchain\.toml run_tests true
            xtask/.* run_tests true
