{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Retained",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "apollo_router_jemalloc_retained",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resident",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "apollo_router_jemalloc_resident",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Metadata",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "apollo_router_jemalloc_metadata",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mapped",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "apollo_router_jemalloc_mapped", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Allocated",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "apollo_router_jemalloc_allocated",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "apollo_router_jemalloc_active", "legendFormat": "__auto" }
   ]
  }
 ]
}