version: "3.9"
services:

  subgraphs:
    build:
      dockerfile: ../dockerfiles/Dockerfile.federation-demo
    ports:
      - 4100:4100
      - 4001:4001
      - 4002:4002
      - 4003:4003
      - 4004:4004
    command: npm run start-services
    environment:
      - JAEGER_HOST=jaeger
    depends_on:
      - jaeger

  gateway:
    container_name: apollo-gateway-fed-2
    build: ../dockerfiles/fed2-demo-gateway
    environment:
      - APOLLO_OTEL_EXPORTER_TYPE=collector
      - APOLLO_OTEL_EXPORTER_HOST=collector
      - APOLLO_OTEL_EXPORTER_PORT=4318
      - APOLLO_SCHEMA_CONFIG_EMBEDDED=true
    volumes:
      - ./supergraph.graphql:/etc/config/supergraph.graphql
    ports:
      - "4200:4000"

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 16686:16686
      - 14268:14268
