FROM node:18-bullseye

WORKDIR /usr/src/app
# TODO: use https://github.com/apollographql/federation-demo once PR #89 lands
RUN git clone -b master https://github.com/apollographql/federation-demo.git . && \
    npm install

