server:
  cors:
    origins:
      - "https://studio.apollographql.com/"
plugins:
  # this plugin takes a path
  # and will read from it everytime a request comes in
  # to check if a client can run a query
  com.example.allow-client-id:
    - header: "x-client-id"
    - path: "allowedClientIds.json"
