[alias]
xtask = "run --locked --package xtask --manifest-path xtask/Cargo.toml --"
fed = "run -p apollo-federation-cli --"

[profile.profiling]
inherits = "release"
debug = true

[env]
# Unset this if you want to change sql queries for caching
SQLX_OFFLINE = "true"
