[alias]
xtask = "run --locked --package xtask --manifest-path xtask/Cargo.toml --"
fed = "run -p apollo-federation-cli --"

[profile.profiling]
inherits = "release"
debug = true

[env]
# In case of the error below when adding or changing an SQL query,
# run `scripts/sqlx-prepare.sh` to update their metadata.
#
#    error: `SQLX_OFFLINE=true` but there is no cached data for this query
SQLX_OFFLINE = "true"
