[package]
name = "connectors-llm"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12", features = ["blocking", "json"] }
tokio = { version = "1.0", features = ["full"] }
base64 = "0.21"
serde_json = "1.0"
dotenv = "0.15"
