[package]
name = "forbid-anonymous-operations"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
anyhow = "1.0.55"
apollo-router = { path = "../../apollo-router" }
async-trait = "0.1.53"
futures = "0.3.21"
http = "0.2.6"
serde_json = "1.0.79"
tokio = { version = "1.17.0", features = ["full"] }
tower = { version = "0.4.12", features = ["full"] }
tracing = "0.1.31"
