version: '2'

services:
  unix-socket-tmp:
    image: busybox
    command: "chmod -R 777 ${REDIS_UNIX_SOCK_CONTAINER_DIR}"
    volumes:
      - '${REDIS_UNIX_SOCK_HOST_DIR}:${REDIS_UNIX_SOCK_CONTAINER_DIR}'
  fred-benchmark:
    depends_on:
      - redis-main
      - redis-cluster-6
      - redis-main-unix-socket
    container_name: "fred-benchmark"
    build:
      context: ../../../
      dockerfile: tests/docker/runners/images/base.dockerfile
      args:
        REDIS_VERSION: "${REDIS_VERSION}"
    networks:
      - fred-tests
    environment:
      RUST_LOG: "${RUST_LOG}"
      REDIS_VERSION: "${REDIS_VERSION}"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      REDIS_USERNAME: "${REDIS_USERNAME}"
    volumes:
      - "../../../bin/benchmark:/project"
      - "../../..:/fred"
      - "~/.cargo/registry:/usr/local/cargo/registry"
    volumes_from:
      - unix-socket-tmp