mod directives;
pub mod errors;
pub(crate) mod helpers;
mod masking;
mod reachability;
mod tagging;
#[cfg(test)]
pub(crate) mod testing;

use apollo_compiler::Schema;
use apollo_compiler::collections::IndexSet;

use crate::composition::Satisfiable;
use crate::composition::Supergraph;
use crate::contract::errors::FilterStep;
use crate::contract::errors::TransformError;
use crate::schema::FederationSchema;

/// Tag filters to apply to a supergraph.
///
/// Validated on construction, so `include` and `exclude` are always disjoint.
#[derive(Debug, Clone, Default)]
pub struct ContractFilters {
    /// Tags to include. Empty includes everything.
    pub(crate) include: IndexSet<String>,
    /// Tags to exclude. Exclusion wins over inclusion.
    pub(crate) exclude: IndexSet<String>,
    /// Mask types that are unreachable from the root operation types.
    pub(crate) hide_unreachable_types: bool,
}

impl ContractFilters {
    /// # Errors
    /// [`TransformError::OverlappingFilters`] if a tag is both included and excluded,
    /// which has no coherent meaning.
    pub fn new(
        include: impl IntoIterator<Item = impl Into<String>>,
        exclude: impl IntoIterator<Item = impl Into<String>>,
        hide_unreachable_types: bool,
    ) -> Result<Self, TransformError> {
        let include: IndexSet<String> = include.into_iter().map(Into::into).collect();
        let exclude: IndexSet<String> = exclude.into_iter().map(Into::into).collect();

        let overlap: Vec<String> = include.intersection(&exclude).cloned().collect();
        if !overlap.is_empty() {
            return Err(TransformError::OverlappingFilters(overlap));
        }

        Ok(Self {
            include,
            exclude,
            hide_unreachable_types,
        })
    }
}

/// Transforms provided supergraph schema to a contract variant.
///
/// Contract variants are generated by applying `@inaccessible` that should be excluded from public
/// API schema. Inaccessible elements are computed based on the contract filters and matching `@tag`
/// on object fields and object, interface, and union types.
pub fn filter_schema(
    supergraph_sdl: &str,
    filters: &ContractFilters,
) -> Result<Supergraph<Satisfiable>, TransformError> {
    // Step 1 goes through `FederationSchema` so that the spec machinery -- `check_or_add`,
    // the `@link` positions API -- keeps the referencer index in step with the edits.
    let mut schema = FederationSchema::new(parse_supergraph(supergraph_sdl)?)
        .map_err(|e| TransformError::InvalidSupergraph(e.to_string()))?;

    // PORT NOTE: JS version was doing some extra validations to handle old v1 supergraphs, it was verifying that
    // - `@tag` is repeatable
    // - `@inaccessible` specifies `SECURITY` purpose
    // - expanding possible directive locations
    // Contracts are generated from an output of a corresponding composition binary - the result is a valid
    // supergraph v2 that either has the `@tag` + `@inaccessible` in it (they are used) OR logic below
    // will populate it with the latest version available

    // Step 1: directive setup. Step 1 is the only step that can add `@link` applications,
    // so it resolves the `@tag`/`@inaccessible`/`@link` names every later step works from.
    let directive_metadata = directives::step1_add_directive_definitions(&mut schema)
        .map_err(|e| TransformError::directive_setup(FilterStep::AddDirectiveDefinitions, e))?;

    // Steps 4-12 edit through the position API, which keeps the referencers in step with
    // every `@tag`/`@inaccessible` they add. Later steps start from those referencers rather
    // than walking the whole schema, so no step may edit the inner schema directly.
    let internal = TransformError::internal;

    // Steps 4-5: tag propagation and matching
    tagging::step4_tag_inheriting(&mut schema, &directive_metadata)
        .map_err(internal(FilterStep::TagInheriting))?;
    tagging::step5_tag_matching(&mut schema, &directive_metadata, filters)
        .map_err(internal(FilterStep::TagMatching))?;

    // Steps 6-11: cascading masking of empty containers
    masking::step6_empty_enum_masking(&mut schema, &directive_metadata)
        .map_err(internal(FilterStep::EmptyEnumMasking))?;
    masking::step7_empty_input_object_masking(&mut schema, &directive_metadata)
        .map_err(internal(FilterStep::EmptyInputObjectMasking))?;
    masking::step8_empty_field_masking(&mut schema, &directive_metadata, filters)
        .map_err(internal(FilterStep::EmptyObjectAndInterfaceFieldMasking))?;
    masking::step9_partial_interface_masking(&mut schema, &directive_metadata)
        .map_err(internal(FilterStep::PartialInterfaceMasking))?;
    masking::step10_empty_object_interface_masking(&mut schema, &directive_metadata)
        .map_err(internal(FilterStep::EmptyObjectAndInterfaceMasking))?;
    masking::step11_empty_union_masking(&mut schema, &directive_metadata)
        .map_err(internal(FilterStep::EmptyUnionMasking))?;

    // Step 12: unreachable type cleanup
    if filters.hide_unreachable_types {
        reachability::step12_unreachable_type_masking(&mut schema, &directive_metadata, filters)
            .map_err(internal(FilterStep::UnreachableTypeMasking))?;
    }

    // Filtering only adds `@inaccessible` to an already composed -- and therefore already
    // satisfiable -- supergraph, so satisfiability is preserved by construction and only the
    // GraphQL validity of the result needs re-checking. Validating the `FederationSchema` keeps
    // the referencers steps 4-12 maintained instead of recomputing them.
    let schema = schema
        .validate_or_return_self()
        .map_err(|(_, e)| TransformError::InvalidFilteredSupergraph(e.to_string()))?;
    Ok(Supergraph::new(schema, Vec::new()))
}

/// Parses the supergraph SDL, adopting orphan extensions so `extend schema` patterns resolve.
fn parse_supergraph(sdl: &str) -> Result<Schema, TransformError> {
    Schema::builder()
        .adopt_orphan_extensions()
        .parse(sdl, "supergraph.graphql")
        .build()
        .map_err(|with_errors| {
            let errors: Vec<_> = with_errors.errors.iter().map(|e| e.to_string()).collect();
            TransformError::InvalidSupergraph(errors.join("; "))
        })
}
