{{/* There may not be much configuration so check that there is something */}}
{{- if index .Values.router.configuration "rhai" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "router.rhaiConfigMapName" . }}
  labels:
    {{- include "router.labels" . | nindent 4 }}
data:
  router.rhai: |
{{- if .Values.rhai.input_file }}
{{ .Files.Get .Values.rhai.input_file | indent 4}}
{{- end }}
{{- end }}
