[package]
name = "compose-your-graphql-router"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
apollo-router = { path = "../../../apollo-router" }
tokio = { version = "1", features = ["full"] }
tower = "0.4"
