binop_separator              = "Front"
blank_lines_upper_bound      = 1
brace_style                  = "SameLineWhere"
combine_control_expr         = true
comment_width                = 125
condense_wildcard_suffixes   = false
control_brace_style          = "AlwaysSameLine"
edition                      = "2021"
empty_item_single_line       = true
enum_discrim_align_threshold = 0
error_on_line_overflow       = false
error_on_unformatted         = false
fn_params_layout             = "Tall"
fn_single_line               = false
force_explicit_abi           = true
force_multiline_blocks       = false
format_code_in_doc_comments  = true
format_macro_bodies          = true
format_macro_matchers        = true
format_strings               = true
hard_tabs                    = false
imports_granularity          = "Crate"
imports_indent               = "Block"
imports_layout               = "HorizontalVertical"
indent_style                 = "Block"
inline_attribute_width       = 0
match_arm_blocks             = true
match_block_trailing_comma   = true
max_width                    = 118
merge_derives                = true
newline_style                = "Auto"
normalize_comments           = true
normalize_doc_attributes     = true
overflow_delimited_expr      = true
remove_nested_parens         = true
reorder_impl_items           = true
reorder_imports              = true
reorder_modules              = true
show_parse_errors            = true
space_after_colon            = true
space_before_colon           = false
spaces_around_ranges         = true
struct_field_align_threshold = 50
struct_lit_single_line       = true
tab_spaces                   = 2
trailing_semicolon           = true
type_punctuation_density     = "Wide"
use_field_init_shorthand     = true
use_small_heuristics         = "Default"
use_try_shorthand            = true
where_single_line            = false
wrap_comments                = true
