extend schema
  @link(url: "https://specs.apollo.dev/federation/v2.12", import: ["@key"])

type Query {
  svc3_item0(id: ID!): Svc3Item0
  svc3_item1(id: ID!): Svc3Item1
  svc3_item2(id: ID!): Svc3Item2
  svc3_item3(id: ID!): Svc3Item3
  svc3_item4(id: ID!): Svc3Item4
  svc3_item5(id: ID!): Svc3Item5
  svc3_item6(id: ID!): Svc3Item6
  svc3_item7(id: ID!): Svc3Item7
  svc3_shared0(id: ID!): Shared0
  svc3_shared1(id: ID!): Shared1
  svc3_shared2(id: ID!): Shared2
  svc3_shared3(id: ID!): Shared3
}

type Svc3Item0 {
  id: ID!
  name: String
  value: Int
}

type Svc3Item1 {
  id: ID!
  name: String
  value: Int
}

type Svc3Item2 {
  id: ID!
  name: String
  value: Int
}

type Svc3Item3 {
  id: ID!
  name: String
  value: Int
}

type Svc3Item4 {
  id: ID!
  name: String
  value: Int
}

type Svc3Item5 {
  id: ID!
  name: String
  value: Int
}

type Svc3Item6 {
  id: ID!
  name: String
  value: Int
}

type Svc3Item7 {
  id: ID!
  name: String
  value: Int
}

type Shared0 @key(fields: "id") {
  id: ID!
  s3_a: String
  s3_b: String
}

type Shared1 @key(fields: "id") {
  id: ID!
  s3_a: String
  s3_b: String
}

type Shared2 @key(fields: "id") {
  id: ID!
  s3_a: String
  s3_b: String
}

type Shared3 @key(fields: "id") {
  id: ID!
  s3_a: String
  s3_b: String
}
