[package]
name = "benchmark_metrics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
subprocess = "0.2"
indicatif = "=0.17.1"
log = "0.4"
pretty_env_logger = "0.5"
clap = { version = "2.33", features = ["yaml"] }
csv = "1.1"
