[workspace]

[package]
name = "integration-test-router"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.64"
apollo-router = {path = "../../apollo-router"}
anyhow = "1.0.56"
rand = "0.8.5"
tower = "0.4.13"
