[package]
name = "custom-global-allocator"
version = "0.1.0"
edition = "2021"

[dependencies]
# The apollo-router/global-allocator feature is enabled by default, disable it here
apollo-router = {path = "../../apollo-router", default-features = false}