extend schema
  @link(url: "https://specs.apollo.dev/federation/v2.11")
  @link(
    url: "https://specs.apollo.dev/connect/v0.4"
    import: ["@connect", "@source"]
  )
  @source(
    name: "api"
    http: { baseURL: "https://api.example.com/" }
  )

interface Detail {
  text: String!
}

type Summary implements Detail {
  text: String!
}

type FullText implements Detail {
  text: String!
}

type Item {
  detail: Detail
}

type Query {
  item: Item
    @connect(
      source: "api"
      http: { GET: "/item" }
      selection: """
        detail: kind->match(
          ["short", {
            __typename: "Summary",
            text: text
          }],
          [@, {
            __typename: "FullText",
            text: text
          }]
        )
      """
    )
}
