schema
  @link(url: "https://specs.apollo.dev/link/v1.0")
  @link(url: "https://specs.apollo.dev/join/v0.5", for: EXECUTION)
  @link(url: "https://specs.apollo.dev/connect/v0.3", for: EXECUTION)
  @join__directive(graphs: [SVC0, SVC1], name: "link", args: {url: "https://specs.apollo.dev/connect/v0.3", import: ["@connect", "@source"]})
  @join__directive(graphs: [SVC0], name: "source", args: {name: "svc_0", http: {baseURL: "https://svc0.example.com"}})
  @join__directive(graphs: [SVC1], name: "source", args: {name: "svc_1", http: {baseURL: "https://svc1.example.com"}})
{
  query: Query
}

directive @join__directive(graphs: [join__Graph!], name: String!, args: join__DirectiveArguments) repeatable on SCHEMA | OBJECT | INTERFACE | FIELD_DEFINITION

directive @join__enumValue(graph: join__Graph!) repeatable on ENUM_VALUE

directive @join__field(graph: join__Graph, requires: join__FieldSet, provides: join__FieldSet, type: String, external: Boolean, override: String, usedOverridden: Boolean, overrideLabel: String, contextArguments: [join__ContextArgument!]) repeatable on FIELD_DEFINITION | INPUT_FIELD_DEFINITION

directive @join__graph(name: String!, url: String!) on ENUM_VALUE

directive @join__implements(graph: join__Graph!, interface: String!) repeatable on OBJECT | INTERFACE

directive @join__type(graph: join__Graph!, key: join__FieldSet, extension: Boolean! = false, resolvable: Boolean! = true, isInterfaceObject: Boolean! = false) repeatable on OBJECT | INTERFACE | UNION | ENUM | INPUT_OBJECT | SCALAR

directive @join__unionMember(graph: join__Graph!, member: String!) repeatable on UNION

directive @link(url: String, as: String, for: link__Purpose, import: [link__Import]) repeatable on SCHEMA

input join__ContextArgument {
  name: String!
  type: String!
  context: String!
  selection: join__FieldValue!
}

scalar join__DirectiveArguments

scalar join__FieldSet

scalar join__FieldValue

enum join__Graph {
  SVC0 @join__graph(name: "svc0", url: "https://svc0.example.com")
  SVC1 @join__graph(name: "svc1", url: "https://svc1.example.com")
}

scalar link__Import

enum link__Purpose {
  """
  `SECURITY` features provide metadata necessary to securely resolve fields.
  """
  SECURITY

  """
  `EXECUTION` features provide metadata necessary for operation execution.
  """
  EXECUTION
}

type Query
  @join__type(graph: SVC0)
  @join__type(graph: SVC1)
{
  svc0_item0(id: ID!): Svc0Item0 @join__field(graph: SVC0) @join__directive(graphs: [SVC0], name: "connect", args: {source: "svc_0", http: {GET: "/items0/{$args.id}"}, selection: "id name value"})
  svc0_item1(id: ID!): Svc0Item1 @join__field(graph: SVC0) @join__directive(graphs: [SVC0], name: "connect", args: {source: "svc_0", http: {GET: "/items1/{$args.id}"}, selection: "id name value"})
  svc0_item2(id: ID!): Svc0Item2 @join__field(graph: SVC0) @join__directive(graphs: [SVC0], name: "connect", args: {source: "svc_0", http: {GET: "/items2/{$args.id}"}, selection: "id name value"})
  svc0_item3(id: ID!): Svc0Item3 @join__field(graph: SVC0) @join__directive(graphs: [SVC0], name: "connect", args: {source: "svc_0", http: {GET: "/items3/{$args.id}"}, selection: "id name value"})
  svc0_item4(id: ID!): Svc0Item4 @join__field(graph: SVC0) @join__directive(graphs: [SVC0], name: "connect", args: {source: "svc_0", http: {GET: "/items4/{$args.id}"}, selection: "id name value"})
  svc0_item5(id: ID!): Svc0Item5 @join__field(graph: SVC0) @join__directive(graphs: [SVC0], name: "connect", args: {source: "svc_0", http: {GET: "/items5/{$args.id}"}, selection: "id name value"})
  svc0_item6(id: ID!): Svc0Item6 @join__field(graph: SVC0) @join__directive(graphs: [SVC0], name: "connect", args: {source: "svc_0", http: {GET: "/items6/{$args.id}"}, selection: "id name value"})
  svc0_item7(id: ID!): Svc0Item7 @join__field(graph: SVC0) @join__directive(graphs: [SVC0], name: "connect", args: {source: "svc_0", http: {GET: "/items7/{$args.id}"}, selection: "id name value"})
  svc0_shared0(id: ID!): Shared0 @join__field(graph: SVC0) @join__directive(graphs: [SVC0], name: "connect", args: {source: "svc_0", http: {GET: "/shared0/{$args.id}"}, entity: true, selection: "id s0_a s0_b"})
  svc0_shared1(id: ID!): Shared1 @join__field(graph: SVC0) @join__directive(graphs: [SVC0], name: "connect", args: {source: "svc_0", http: {GET: "/shared1/{$args.id}"}, entity: true, selection: "id s0_a s0_b"})
  svc0_shared2(id: ID!): Shared2 @join__field(graph: SVC0) @join__directive(graphs: [SVC0], name: "connect", args: {source: "svc_0", http: {GET: "/shared2/{$args.id}"}, entity: true, selection: "id s0_a s0_b"})
  svc0_shared3(id: ID!): Shared3 @join__field(graph: SVC0) @join__directive(graphs: [SVC0], name: "connect", args: {source: "svc_0", http: {GET: "/shared3/{$args.id}"}, entity: true, selection: "id s0_a s0_b"})
  svc1_item0(id: ID!): Svc1Item0 @join__field(graph: SVC1) @join__directive(graphs: [SVC1], name: "connect", args: {source: "svc_1", http: {GET: "/items0/{$args.id}"}, selection: "id name value"})
  svc1_item1(id: ID!): Svc1Item1 @join__field(graph: SVC1) @join__directive(graphs: [SVC1], name: "connect", args: {source: "svc_1", http: {GET: "/items1/{$args.id}"}, selection: "id name value"})
  svc1_item2(id: ID!): Svc1Item2 @join__field(graph: SVC1) @join__directive(graphs: [SVC1], name: "connect", args: {source: "svc_1", http: {GET: "/items2/{$args.id}"}, selection: "id name value"})
  svc1_item3(id: ID!): Svc1Item3 @join__field(graph: SVC1) @join__directive(graphs: [SVC1], name: "connect", args: {source: "svc_1", http: {GET: "/items3/{$args.id}"}, selection: "id name value"})
  svc1_item4(id: ID!): Svc1Item4 @join__field(graph: SVC1) @join__directive(graphs: [SVC1], name: "connect", args: {source: "svc_1", http: {GET: "/items4/{$args.id}"}, selection: "id name value"})
  svc1_item5(id: ID!): Svc1Item5 @join__field(graph: SVC1) @join__directive(graphs: [SVC1], name: "connect", args: {source: "svc_1", http: {GET: "/items5/{$args.id}"}, selection: "id name value"})
  svc1_item6(id: ID!): Svc1Item6 @join__field(graph: SVC1) @join__directive(graphs: [SVC1], name: "connect", args: {source: "svc_1", http: {GET: "/items6/{$args.id}"}, selection: "id name value"})
  svc1_item7(id: ID!): Svc1Item7 @join__field(graph: SVC1) @join__directive(graphs: [SVC1], name: "connect", args: {source: "svc_1", http: {GET: "/items7/{$args.id}"}, selection: "id name value"})
  svc1_shared0(id: ID!): Shared0 @join__field(graph: SVC1) @join__directive(graphs: [SVC1], name: "connect", args: {source: "svc_1", http: {GET: "/shared0/{$args.id}"}, entity: true, selection: "id s1_a s1_b"})
  svc1_shared1(id: ID!): Shared1 @join__field(graph: SVC1) @join__directive(graphs: [SVC1], name: "connect", args: {source: "svc_1", http: {GET: "/shared1/{$args.id}"}, entity: true, selection: "id s1_a s1_b"})
  svc1_shared2(id: ID!): Shared2 @join__field(graph: SVC1) @join__directive(graphs: [SVC1], name: "connect", args: {source: "svc_1", http: {GET: "/shared2/{$args.id}"}, entity: true, selection: "id s1_a s1_b"})
  svc1_shared3(id: ID!): Shared3 @join__field(graph: SVC1) @join__directive(graphs: [SVC1], name: "connect", args: {source: "svc_1", http: {GET: "/shared3/{$args.id}"}, entity: true, selection: "id s1_a s1_b"})
}

type Shared0
  @join__type(graph: SVC0, key: "id")
  @join__type(graph: SVC1, key: "id")
{
  id: ID!
  s0_a: String @join__field(graph: SVC0)
  s0_b: String @join__field(graph: SVC0)
  s1_a: String @join__field(graph: SVC1)
  s1_b: String @join__field(graph: SVC1)
}

type Shared1
  @join__type(graph: SVC0, key: "id")
  @join__type(graph: SVC1, key: "id")
{
  id: ID!
  s0_a: String @join__field(graph: SVC0)
  s0_b: String @join__field(graph: SVC0)
  s1_a: String @join__field(graph: SVC1)
  s1_b: String @join__field(graph: SVC1)
}

type Shared2
  @join__type(graph: SVC0, key: "id")
  @join__type(graph: SVC1, key: "id")
{
  id: ID!
  s0_a: String @join__field(graph: SVC0)
  s0_b: String @join__field(graph: SVC0)
  s1_a: String @join__field(graph: SVC1)
  s1_b: String @join__field(graph: SVC1)
}

type Shared3
  @join__type(graph: SVC0, key: "id")
  @join__type(graph: SVC1, key: "id")
{
  id: ID!
  s0_a: String @join__field(graph: SVC0)
  s0_b: String @join__field(graph: SVC0)
  s1_a: String @join__field(graph: SVC1)
  s1_b: String @join__field(graph: SVC1)
}

type Svc0Item0
  @join__type(graph: SVC0)
{
  id: ID!
  name: String
  value: Int
}

type Svc0Item1
  @join__type(graph: SVC0)
{
  id: ID!
  name: String
  value: Int
}

type Svc0Item2
  @join__type(graph: SVC0)
{
  id: ID!
  name: String
  value: Int
}

type Svc0Item3
  @join__type(graph: SVC0)
{
  id: ID!
  name: String
  value: Int
}

type Svc0Item4
  @join__type(graph: SVC0)
{
  id: ID!
  name: String
  value: Int
}

type Svc0Item5
  @join__type(graph: SVC0)
{
  id: ID!
  name: String
  value: Int
}

type Svc0Item6
  @join__type(graph: SVC0)
{
  id: ID!
  name: String
  value: Int
}

type Svc0Item7
  @join__type(graph: SVC0)
{
  id: ID!
  name: String
  value: Int
}

type Svc1Item0
  @join__type(graph: SVC1)
{
  id: ID!
  name: String
  value: Int
}

type Svc1Item1
  @join__type(graph: SVC1)
{
  id: ID!
  name: String
  value: Int
}

type Svc1Item2
  @join__type(graph: SVC1)
{
  id: ID!
  name: String
  value: Int
}

type Svc1Item3
  @join__type(graph: SVC1)
{
  id: ID!
  name: String
  value: Int
}

type Svc1Item4
  @join__type(graph: SVC1)
{
  id: ID!
  name: String
  value: Int
}

type Svc1Item5
  @join__type(graph: SVC1)
{
  id: ID!
  name: String
  value: Int
}

type Svc1Item6
  @join__type(graph: SVC1)
{
  id: ID!
  name: String
  value: Int
}

type Svc1Item7
  @join__type(graph: SVC1)
{
  id: ID!
  name: String
  value: Int
}
