[package]
name = "file-uploads"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
anyhow = "1"
apollo-router = { path = "../../../apollo-router" }
async-trait = "0.1"
schemars = { version = "0.8", features = ["url"] }
serde = "1"
serde_json = "1"
tokio = { version = "1", features = ["full"] }
tower = { version = "0.4", features = ["full"] }
tracing = "0.1"
hyper = { version = "0.14.27", features = ["client"] }
multer = "2.1"
reqwest = { version = "0.11", features = ["json", "multipart", "stream"] }
serde_json_bytes = "0.2.2"