{{- if .Values.managedFederation.apiKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "router.managedFederation.apiSecretName" . }}
  labels:
    {{- include "router.labels" . | nindent 4 }}
    {{- if .Values.extraLabels }}
    {{- include "apollographql.templatizeExtraLabels" . | trim | nindent 4 }}
    {{- end }}
data:
  {{ (.Values.managedFederation.existingSecretKeyRefKey | default "managedFederationApiKey") }}: {{ default "MISSING" .Values.managedFederation.apiKey | b64enc | quote }}
{{- end }}
