name: 'Delete Oldest Nightly Images'
run-name: "Deleting ${{ inputs.num_old_versions_to_delete }} oldest nightlies"
on:
  workflow_dispatch:
    inputs:
      num_old_versions_to_delete:
        description: 'Number of oldest images to delete, both nightly/router and helm-charts-nightly/router'
        required: true
        type: number 
jobs:
  delete-images:
    name: Delete images
    steps:
      - name: nightly/docker 
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'nightly/router'
          package-type: 'container'
          num-old-versions-to-delete: ${{ inputs.num_old_versions_to_delete }}
      - name: helm-charts-nightly/router
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'helm-charts-nightly/router'
          package-type: 'container'
          num-old-versions-to-delete: ${{ inputs.num_old_versions_to_delete }}