[tools]
# renovate-automation: rustc version
rust = { version = "1.96.1", profile = "default" }
"aqua:cargo-bins/cargo-binstall" = "1.21.0"
"cargo:cargo-nextest" = "0.9.70"
"cargo:cargo-deny" = "0.20.2"
"cargo:cargo-edit" = "0.13.0"
"cargo:cargo-about" = "0.9.1"
"cargo:cargo-insta" = "1.38.0"
"cargo:htmlq" = "0.4.0"
"cargo:cargo-watch" = "8.5.3"
"cargo:cargo-machete" = "0.9.0"
"cargo:cargo-llvm-cov" = "0.8.7"
"cargo:typos-cli" = "1.31.1"
protoc = "35.1"
gh = "2.96.0"
helm = "4.2.3"
helm-docs = "1.14.2"
yq = "4.53.3"
jq = "1.8.2"
redis = "8.8.1"
